backend:
  name: git-gateway
  branch: main # Si tu rama principal es 'master', cambia 'main' por 'master'

media_folder: "images"
public_folder: "images"

collections:
  - name: "inicio"
    label: "Página de Inicio"
    files:
      - name: "principal"
        label: "Contenido Principal"
        file: "index.html"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Relator", name: "relator", widget: "string"}
          - {label: "Mensaje de Bienvenida", name: "mensaje", widget: "text"}
