backend:
  name: git-gateway
  branch: main

media_folder: "images"
public_folder: "images"

collections:
  - name: "inicio"
    label: "Página de Inicio"
    files:
      - name: "principal"
        label: "Contenido Principal"
        file: "index.html"
        fields:
          - {label: "Título Principal", name: "titulo", widget: "string"}
          - {label: "Nombre del Relator", name: "relator", widget: "string"}
          - {label: "Mensaje de Bienvenida", name: "mensaje", widget: "text"}
